/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.monster.vista;

import ec.edu.monster.controlador.ConvUniControlador;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ConvUniEscVista extends javax.swing.JFrame {

    /**
     * Creates new form ConvUniEscVista
     */
    private FondoPanel fondo = new FondoPanel("E:\\USER\\Documents\\ESPE\\Octavo Semestre\\Arquitectura de Software\\CONV_UNI\\01. CONV_UNI_SOAP_JAVA_GUARDERAS\\02. CLIESC\\WS_CONVUNI_SOAPJAVA_CLIESC\\src\\resources\\imagenes\\monster2.jpg");
    
    public ConvUniEscVista() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtKG.addKeyListener(new java.awt.event.KeyAdapter(){
            public void keyTyped(java.awt.event.KeyEvent evento){
                char c = evento.getKeyChar();
                if(!Character.isDigit(c) && c != '.'){
                    evento.consume();
                }
            }
        });
        
        txtLB.addKeyListener(new java.awt.event.KeyAdapter(){
            public void keyTyped(java.awt.event.KeyEvent evento){
                char c = evento.getKeyChar();
                if(!Character.isDigit(c) && c != '.'){
                    evento.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lvlLbKg = new javax.swing.JLabel();
        llblKgLb = new javax.swing.JLabel();
        txtKG = new javax.swing.JTextField();
        txtLB = new javax.swing.JTextField();
        btnKbLb = new javax.swing.JButton();
        btnLbKg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConvLb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtConvKg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        llblKgLb1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kg ↔ Lb");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lvlLbKg.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lvlLbKg.setForeground(new java.awt.Color(255, 255, 255));
        lvlLbKg.setText("Convertir Libras a Kilos");
        lvlLbKg.setName("lblLbKg"); // NOI18N

        llblKgLb.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        llblKgLb.setForeground(new java.awt.Color(255, 255, 255));
        llblKgLb.setText("Convertir Kilos a Libras");
        llblKgLb.setName("lblKgLb"); // NOI18N

        txtKG.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N

        txtLB.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N

        btnKbLb.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        btnKbLb.setText("Convertir");
        btnKbLb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKbLbActionPerformed(evt);
            }
        });

        btnLbKg.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        btnLbKg.setText("Convertir");
        btnLbKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLbKgActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kg");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("lb");

        txtConvLb.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtConvLb.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtConvLb.setEnabled(false);
        txtConvLb.setOpaque(false);
        txtConvLb.setRequestFocusEnabled(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("lb");

        txtConvKg.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtConvKg.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtConvKg.setEnabled(false);
        txtConvKg.setOpaque(false);
        txtConvKg.setRequestFocusEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kg");

        llblKgLb1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        llblKgLb1.setForeground(new java.awt.Color(255, 255, 255));
        llblKgLb1.setText("CONVERSIÓN DE UNIDADES - SOAP JAVA");
        llblKgLb1.setName("lblKgLb"); // NOI18N

        btnLogOut.setBackground(new java.awt.Color(242, 79, 79));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogOut.setText("Cerrar Sesión");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(llblKgLb1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlLbKg, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(llblKgLb, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtKG, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(btnKbLb)
                                .addGap(26, 26, 26)
                                .addComponent(txtConvLb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtLB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(btnLbKg)
                                .addGap(31, 31, 31)
                                .addComponent(txtConvKg, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)))
                        .addGap(47, 390, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(llblKgLb1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(llblKgLb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKG, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKbLb)
                    .addComponent(jLabel1)
                    .addComponent(txtConvLb, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addComponent(lvlLbKg)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtConvKg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(btnLbKg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKbLbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKbLbActionPerformed
        // TODO add your handling code here:
        double kg = Double.parseDouble(txtKG.getText());
        
        ConvUniControlador control = new ConvUniControlador();
        double lb = control.convKgLb(kg);
        if(lb == -1){
            JOptionPane.showMessageDialog(null,"El servicio web no está disponible o falló la conexión.","Error",JOptionPane.ERROR_MESSAGE);
        }else if(lb == -2){
            JOptionPane.showMessageDialog(null,"Se produjo un error inesperado.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            txtConvLb.setText(String.valueOf(lb));
        }
    }//GEN-LAST:event_btnKbLbActionPerformed

    private void btnLbKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLbKgActionPerformed
        // TODO add your handling code here:
        double lb = Double.parseDouble(txtLB.getText());
        
        ConvUniControlador control = new ConvUniControlador();
        double kg = control.convLbKg(lb);
        if(kg == -1){
            JOptionPane.showMessageDialog(null,"El servicio web no está disponible o falló la conexión.","Error",JOptionPane.ERROR_MESSAGE);
        }else if(kg == -2){
            JOptionPane.showMessageDialog(null,"Se produjo un error inesperado.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            DecimalFormat df = new DecimalFormat("#.00");
            txtConvKg.setText(String.valueOf(kg));
        }
        
    }//GEN-LAST:event_btnLbKgActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        dispose();
        LogIn login = new LogIn();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvUniEscVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvUniEscVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvUniEscVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvUniEscVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvUniEscVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKbLb;
    private javax.swing.JButton btnLbKg;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel llblKgLb;
    private javax.swing.JLabel llblKgLb1;
    private javax.swing.JLabel lvlLbKg;
    private javax.swing.JTextField txtConvKg;
    private javax.swing.JTextField txtConvLb;
    private javax.swing.JTextField txtKG;
    private javax.swing.JTextField txtLB;
    // End of variables declaration//GEN-END:variables
}
